---
language: c
services:
  - docker

# Run everything in a Fedora container (created in before_install) so
# that we're not fighting with deps on two distros.
# Use the same paths both inside and outside the container so that
# the coverage stuff doesn't get confused.
env:
  DOCKER_RUN="docker run -v $PWD:$PWD --workdir $PWD rpminspect/test-env"

before_install:
  - docker build -t rpminspect/test-env -f Dockerfile.test .

script:
  - $DOCKER_RUN meson setup build --werror -Db_coverage=true
  - pip-3 install --user cpp-coveralls

  # Stop after the first failure, to keep the output more readable
  - |
    $DOCKER_RUN ninja -v -C build &&
    $DOCKER_RUN ninja -C build coverage &&
    $DOCKER_RUN meson test -C build -v

after_success:
  - coveralls -b build --gcov-options '\-lp'
